apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: mi-pod
  name: mi-pod
spec:
  containers:
  - image: fedek3/workshop-uns:latest
    name: mi-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}