apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mi-pod
  name: mi-pod
spec:
  ports:
  - name: "80"
    nodePort: 30100
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mi-pod
  type: NodePort
status:
  loadBalancer: {}
