apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mi-deploy
  name: mi-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mi-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mi-deploy
    spec:
      containers:
      - image: fedek3/workshop-uns:v0.3.0
        name: workshop-uns
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500
            memory: 512Mb
          requests:
            cpu: 100
            memory: 256Mb
        securityContext:
          runAsUser: 1000
          runAsGroup: 3000
          fsGroup: 2000
          fsGroupChangePolicy: "OnRootMismatch"
          allowPrivilegeEscalation: false
status: {}
