apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mi-pod
  name: mi-pod
spec:
  containers:
  - image: fedek3/workshop-uns:v0.2.0
    name: mi-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}